### ISSUE TITLE
Make Application Trait

### ISSUE THREAD

**Issue by oddz** [mesour/components#1]
I'm using this with Laravel overriding the Laravel App with my own custom application that implements IApplication interface. It would be nice if I didn't have to repeat the all the logic in each one of the interfaces methods. This could easily be done with a base application trait. Just a thought. I could probably easily fork this and make it myself.

In regards to laravel specifically it seems dirty to have two separate applications so I'm merging them into one which seems like the correct approach.

**Comment by oddz** [comment]
I just ended up registering the app in the service container as a separate binding.

```
		$this->app->singleton(IApplication::class,function() {
			$theApp = new UiApplication();
			$theApp->setRequest($_REQUEST);
			return $theApp;
		});
		$this->app->alias(IApplication::class,'uiapp');
```

**Comment by mesour** [comment]
Issue moved to [mesour/laravel-bridges #1](https://github.com/mesour/laravel-bridges/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
