### ISSUE TITLE
mesour/components v3.0.4 requires nette/utils ~2.3.7 -> satisfiable by nette/utils[v2.3.10, v2.3.7, v2.3.8, v2.3.9, v2.3.x-dev] but these conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by jarda256** [mesour/components#4]
Hi, i wanted to install your datagrid 3.0.*@beta (using your nette brige) on my nette project, but composer gave me conflict with requirement. O my new nette project I have nette/utils ^2.4 . Can I do something to run your datagrid ?

Edit: mesour/filter has also conflict with requirements

**Comment by mesour** [comment]
Yes, you have right. Thank you for report.

Fixed in 3.0.5: https://github.com/mesour/components/releases/tag/v3.0.5
